baseURL: 'https://rugu.dev/'
languageCode: 'en-us'
title: 'ugur'
theme: 'simplerugu'

params:
  authorImage: "/ugur_img.jpg"
  connect:
    - twitter: 'https://twitter.com/kugurerdem'
    - github: 'https://github.com/kugurerdem'
    - hackernews: 'https://news.ycombinator.com/user?id=kugurerdem'
    - rss: '/en/index.xml'
  email: "ugur@rugu.dev"
  author: "Uğur Erdem Seyfi"

defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/english
    languageName: English
    weight: 0
    params:
      description: "A software developer with a hacker's attitude, interested in philosophy and psychology"
      menu:
        home: 'Home'
        wisdom: 'Wisdom'
      contact: 'Contact'
      collaborate: "See my [CV](/en/cv) to decide if you want to work with me."

  tr:
    contentDir: content/turkce
    languageName: Turkce
    weight: 1
    params:
      description: "hacker kafalı yazılımcı, matematik mezunu '23, felsefe ve psikoloji ile ilgileniyor"
      menu:
        home: 'Anasayfa'
        wisdom: 'Bilgelik'
      contact: 'İletişim'
